site_name: PyMindWave2 Docs
repo_url: https://github.com/PrinceEGY/pymindwave2
repo_name: PrinceEGY/pymindwave2

theme:
  name: material
  features:
    - toc.title
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tabs.annotation
    - content.code.copy
  language: en

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv

          options:
            docstring_style: google
            members_order: source
            merge_init_into_class: true
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            separate_signature: true
            signature_crossrefs: true
            show_signature_annotations: true
            docstring_options:
              ignore_init_summary: true

  - include-markdown

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Examples: examples.md
  - API Documentaion:
      - MindwaveMobile2: api/headset.md
      - Session: api/session.md
      - Events: api/events.md
      - Enums: api/enums.md
      - ThinkGear Connector: api/tg_connector.md
      - Logger: api/logger.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/PrinceEGY/" target="_blank" rel="noopener">PrinceEGY</a>
